allowBuilds:
  "@prisma/engines": true
  argon2: true
  esbuild: true
  prisma: true
  unrs-resolver: true
overrides:
  deepmerge-ts: 8.0.0
minimumReleaseAgeExclude:
  - "@next/env@16.3.3"
  - "@next/eslint-plugin-next@16.3.3"
  - "@next/swc-darwin-arm64@16.3.3"
  - "@next/swc-darwin-x64@16.3.3"
  - "@next/swc-linux-arm64-gnu@16.3.3"
  - "@next/swc-linux-arm64-musl@16.3.3"
  - "@next/swc-linux-x64-gnu@16.3.3"
  - "@next/swc-linux-x64-musl@16.3.3"
  - "@next/swc-win32-arm64-msvc@16.3.3"
  - "@next/swc-win32-x64-msvc@16.3.3"
  - "@prisma/config@7.10.0"
  - "@prisma/debug@7.10.0"
  - "@prisma/engines@7.10.0"
  - "@prisma/fetch-engine@7.10.0"
  - "@prisma/get-platform@7.10.0"
  - eslint-config-next@16.3.3
  - next@16.3.3
  - prisma@7.10.0
  - "@better-auth/core@1.7.2"
  - "@better-auth/drizzle-adapter@1.7.2"
  - "@better-auth/kysely-adapter@1.7.2"
  - "@better-auth/memory-adapter@1.7.2"
  - "@better-auth/mongo-adapter@1.7.2"
  - "@better-auth/prisma-adapter@1.7.2"
  - "@better-auth/telemetry@1.7.2"
  - better-auth@1.7.2
  - resend@6.24.0
